# docker/docker-compose.yml
version: '3'

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: ordinals
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../../database/postgres_data:/var/lib/postgresql/data
